### ISSUE TITLE
Should have a list for tank mania implementations

### ISSUE THREAD

**Issue by thinxer** [xinhaoyuan/TankMania#1]
As this is a homework, I believe that there should be a lot implementations, some with AI. It may be better to list the implementations here.

**Comment by thinxer** [comment]
Here's mine:

https://github.com/thinxer/tanx/

Featuring a cool UI, sound effects and a carefully designed GameLoop.

**Comment by xinhaoyuan** [comment]
Agree. But I don't have the list. Instead I put the list on the wiki page. You can and add your project link to it
